# .project metadata for Litmus
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "litmus"
name: "Litmus"
description: "Litmus is an open source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way"
type: "project"
project_lead: "amityt" # TODO: AUTO-DETECTED — please verify
slack_channels: # TODO: AUTO-DETECTED — please verify the channel(s) below
  - name: "#CNXNB0ZTN"
    link: "https://kubernetes.slack.com/messages/CNXNB0ZTN"
    primary: true
  - name: "#litmus"
  - name: "#litmus-dev"

maturity_log:
  - phase: "incubating"
    date: "2020-06-25T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/288" # TODO: AUTO-DETECTED — please verify

repositories: # TODO: AUTO-DETECTED primary — please verify
  - url: "https://github.com/litmuschaos/litmus"
    primary: true
    # tags: [core, sig-apps] # Optional

website: "https://litmuschaos.io/"

artwork: "https://landscape.cncf.io/logos/litmus.svg"

adopters:
  path: "https://github.com/litmuschaos/litmus/blob/master/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "litmuschaos/litmus"

social:
  twitter: "https://twitter.com/litmuschaos"

security:
  policy:
    path: "https://github.com/litmuschaos/litmus/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/litmuschaos/litmus/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/litmuschaos/litmus/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/litmuschaos/litmus/blob/master/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/litmuschaos/litmus/blob/master/README.md"

landscape:
  category: "Observability and Analysis"
  subcategory: "Chaos Engineering"

# CLOMonitor Score: 86/100
# Documentation: 97 | License: 100 | Best Practices: 68 | Security: 73
